[package]
name = "mev_sol"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
serde_json = "1.0.132"
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
anyhow = "1.0.100"
solana-client = "3.1.5"
solana-sdk = "3.0.0"