[workspace]
members = [
  "connections",
  "protocols",
  "scheduler",
  "searcher",
  "worker",
  "add_worker",
  "rem_worker"
]

resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
